{% set name = "cardiac-geometriesx" %}
{% set python_min = "3.10" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cardiac_geometriesx-{{ version }}.tar.gz
  sha256: 215be38d5f61dcd59bff5fd36e0222d2d15ae9b6378ce1434845496433bb5ed9

build:
  number: 0
  noarch: python
  entry_points:
    - "geox=cardiac_geometries.cli:app"
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - adios4dolfinx
    - structlog
    - cardiac-geometries-core
    - scifem
    - fenics-dolfinx
    - libgl

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pip
  imports:
    - cardiac_geometries
  source_files:
    - tests/
    - pyproject.toml
  commands:
    - geox --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests


about:
  home: https://github.com/ComputationalPhysiology/cardiac-geometriesx
  summary: Cardiac-geometries for dolfinx
  license: MIT
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/cardiac-geometriesx/
  dev_url: https://github.com/ComputationalPhysiology/cardiac-geometriesx

extra:
  recipe-maintainers:
    - finsberg
