{% set name = "cardiac-geometriesx" %}
{% set python_min = "3.10" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cardiac_geometriesx-{{ version }}.tar.gz
  sha256: d26b48990068ef04a5b7dba1fa9430996b360ac5392fe2d9825bb9010a344cc3

build:
  number: 0
  noarch: python
  entry_points:
    - "geox=cardiac_geometries.cli:app"
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - adios4dolfinx
    - structlog
    - cardiac-geometries-core
    - scifem
    - fenics-dolfinx
    - libgl

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pip
  imports:
    - cardiac_geometries
  source_files:
    - tests/
    - pyproject.toml
  commands:
    - geox --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests


about:
  home: https://github.com/ComputationalPhysiology/cardiac-geometriesx
  summary: Cardiac-geometries for dolfinx
  license: MIT
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/cardiac-geometriesx/
  dev_url: https://github.com/ComputationalPhysiology/cardiac-geometriesx

extra:
  recipe-maintainers:
    - finsberg
